### PR TITLE
Update to 2.53, redesign the build system.

### PR DESCRIPTION
**Pull request by ezdiy**
The way this is currently used is a lovecraftian fever of unmaintainable nightmare. Let's try to tackle this cthulthu:

* k2pdfopt is left in *pristine* for as much as possible, so that we get drag&drop code updates for future versions. For now the small patches for android etc will be done by koreader-base, but it may devolve into a tracking fork again if our changes to k2pdfopt will ever become actually invasive.
* Keep our makefile strictly utilitarian to just build the library and nothing else
* mupdf, tess and leptonica are now built in base, we get em via CFLAGS/LDFLAGS.
* patches to mupdf, tess and leptonica are explicitly pre-built via heuristic in [make_patches.sh](https://github.com/ezdiy/libk2pdfopt/blob/master/make_patches.sh). Those are then applied during build in https://github.com/koreader/koreader-base/pull/1203 this may seem needlessly complicated, but it helps to keep things transparent what those patches are actually about compared to that horrible file-replacement thing. It also scales to bumping versions of those libraries (to an extent).

todo: Darwin build.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/libk2pdfopt/39)

### CODE REVIEW

**Comment by Frenzie** [comment]
Which parts of the diff/result should I look at? Basically just the Makefile?

**Comment by ezdiy** [comment]
Ye, i should probably split it into one doing the flat replace and second with my changes to port to new APIs.

**Review by Frenzie — COMMENTED** [review]
All looks like good concepts to me. :+1:

**Comment by NiLuJe** [comment]
What he said ;).

(I've just realized that I wasn't watching this repo ^^).

**Comment by ezdiy** [comment]
Hmm, people are looking, better squash the bloat inbetween so they don't judge :>

**Comment by Frenzie** [comment]
Superseded by #49. Thanks for all the effort @ezdiy :-)

**Pull request closed without merging**
