### PR TITLE
Update to k2pdfopt 2.42

### PR DESCRIPTION
**Pull request by NiLuJe**
Massively untested.

May eat your firstborn's soul.

### CODE REVIEW

**Comment by NiLuJe** [comment]
I basically went as far as making sure ffi-cdecl wasn't complaining anymore.

I have no idea how any of this works beyond that :D.

**Comment by Frenzie** [comment]
/grins

I don't either, but I think that as long as the patches and the `kopt*` files in root are okay it might work.

**Comment by chrox** [comment]
I will take a look. If I remember correctly we have some unit-test cases for the reflowing and ocr functionality.

**Comment by Frenzie** [comment]
@chrox Thanks! Yes, they're available over [here](https://github.com/koreader/koreader-base/blob/aa8141f5b8076f7cf14dec7e2d8a2eb5dc4a9389/spec/unit/koptcontext_spec.lua). I was just about to run them myself within an hour or so. :-)

**Comment by chrox** [comment]
@Frenzie Just go ahead. If the unit-tests do not complain we can safely merge this according to my experience.

**Comment by Frenzie** [comment]
I was working on updating my cv (finished now, "within an hour or so" ;-) ) and I'm also writing a motivational letter, so it's not quite at the top of my list of priorities atm. I've got everything ready to run the tests, anyway. Fingers crossed that when I do, they'll pass.

**Comment by Frenzie** [comment]
@NiLuJe I got a compilation error:

```
willuslib/wmupdfinfo.c:31:10: fatal error: mupdf/pdf.h: No such file or directory
 #include <mupdf/pdf.h>
```

**Comment by NiLuJe** [comment]
Yup, missed a `/*` `*/` bracket -_-".

**Comment by Frenzie** [comment]
It mostly seems to work, but there does seem to be one tiny problem:

screenshot_2018-11-26_19-56-47

https://github.com/koreader/koreader-base/blob/aa8141f5b8076f7cf14dec7e2d8a2eb5dc4a9389/spec/unit/koptcontext_spec.lua#L132-L139

Otoh I would guess at a wrong index or a lack of initialization or something but I haven't looked into it.

**Comment by NiLuJe** [comment]
Yeah, probably `getTOCRWord` blowing up in the weird Tesseract C API shim...

**Comment by NiLuJe** [comment]
I'd say strncmp crashing on the NULL pointer returned by k2pdfopt_tocr_get_language in k2pdfopt_tocr_init @ koptocr.c

**Comment by NiLuJe** [comment]
I'm not quite sure I understand the reasoning behind the "let's reinit tesseract if it's currently initialized for this language" (which i think is what this is supposed to do?), but this should be easily fixed.

(Either by guarding against NULL pointers, or returning an empty string instead of a NULL ptr).

**Comment by NiLuJe** [comment]
Did both, because that makes the logic slightly less obtuse ;).

Possibly fixes the crash as a bonus :D.

**Comment by Frenzie** [comment]
Time to sleep, so if you'd like me to test it see you in 20 hours. ;-)

**Comment by Frenzie** [comment]
Okay, the unit tests pass and some playing around with it in the GUI also didn't crash, so I reckon it's ready to go.

Could you rebase it into (probably) two commits?

1. vanilla + drop files
2. KOReader patch set

**Comment by Frenzie** [comment]
Or at least a more logical slightly condensed order, like:

1. vanilla
2. drop files
3. patch set
4. updated patch set

(and then rebase on GH instead of squash, of course)

**Comment by NiLuJe** [comment]
Sure! Later tonight/tomorrow though, no git setup on this box ;).

Thanks for going to the trouble of testing this ;).

**Comment by NiLuJe** [comment]
Self-ping so this stays at the top of my GH page and don't forget about it ;p.

**Comment by NiLuJe** [comment]
Huh, ordering didn't exactly make it through the rebase because the drop commit didn't change, but, eh, good enough ;).

**Comment by NiLuJe** [comment]
@Frenzie : I'll leave the choice of rebase or merge commit to you, sorry this took so long -_-".

**Comment by Frenzie** [comment]
I think rebase is clearer here. :-)

**Pull request merged**
