### PR TITLE
Possibly fix undefined symbol issue

### PR DESCRIPTION
**Pull request by NiLuJe**
Hopefully it'll be as simple as that...

### CODE REVIEW

**Comment by NiLuJe** [comment]
Currently checking if that builds, but luarocks is being difficult...

**Comment by Frenzie** [comment]
I bought a new 1 TB SSD so I wouldn't have to struggle for disk space against Android images and such and I have a whopping 132 GB remaining. Even though the Android images remain on my 2 TB HDD (195 GB free).

/random remark about computers being difficult

Crude screens, not for sensitive souls:

**Comment by NiLuJe** [comment]
:D.

In the same vein, here's what I'm doing to play nice with luarocks 3:

```diff
diff --git a/Makefile.third b/Makefile.third
index 7a5064d..ef20fac 100644
--- a/Makefile.third
+++ b/Makefile.third
@@ -598,8 +598,6 @@ $(LUA_SPORE_ROCK): $(THIRDPARTY_DIR)/lua-Spore/CMakeLists.txt
                -DLUA_SPORE_VER=$(LUA_SPORE_VER) -DLD="$(CC)" \
                -DCC="$(CC)" -DCFLAGS="$(CFLAGS) -I$(LUAJIT_DIR)/src" \
                -DLUAROCKS=$(if $(DARWINHOST),"luarocks --lua-dir=/usr/local/opt/lua@5.1",luarocks) \
-               -DLUA_INCDIR=$(if $(DARWINHOST),/usr/local/opt/lua@5.1/include/lua5.1,"$(LUAJIT_DIR)/src") \
-               -DLUA_LIBDIR=$(if $(DARWINHOST),/usr/local/opt/lua@5.1/lib,"$(CURDIR)/$(dir $(LUAJIT_LIB))") \
                $(if $(ANDROID),-DLIBFLAG="$(LDFLAGS) $(CURDIR)/$(LUAJIT_LIB) -nostartfiles",) \
                $(CURDIR)/$(THIRDPARTY_DIR)/lua-Spore && \
                $(MAKE)
diff --git a/thirdparty/lua-Spore/CMakeLists.txt b/thirdparty/lua-Spore/CMakeLists.txt
index e960c82..41583a8 100644
--- a/thirdparty/lua-Spore/CMakeLists.txt
+++ b/thirdparty/lua-Spore/CMakeLists.txt
@@ -25,7 +25,6 @@ if(DEFINED LIBFLAG)
     set(BUILD_CMD "${BUILD_CMD} LIBFLAG=\"${LIBFLAG}\"")
 endif()
 set(BUILD_CMD "${BUILD_CMD} CC=\"${CC}\" CFLAGS=\"${CFLAGS}\" LD=\"${LD}\"")
-set(BUILD_CMD "${BUILD_CMD} LUA_INCDIR=\"${LUA_INCDIR}\" LUA_LIBDIR=\"${LUA_LIBDIR}\"")

 set(PATCH_CMD sh -c "mkdir -p doc && ${ISED} \"s| 'luasocket|--'luasocket|g\" ${LUA_SPORE_ROCKSPEC}")
```

Also, because that's hilarious:

```
┌─(niluje@illyria:pts/14)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(2.88:32%:19:30:%)── luarocks config --verbose --lua-dir=/usr --lua-version=jit-2.0.5                                                                                                                                                                                                                                                                 ──(Wed, Jan 09)─┘
- correct config to .config ? ([Y]es/[N]o/[E]dit/[A]bort) -n

Error: Lua interpreter not found at /usr
Tried:  /usr/bin/luajit-2.0.5
        /usr/bin/luajit-205
        /usr/bin/lua-jit-2.0.5
        /usr/bin/lua-jit-205
        /usr/bin/lua
        /usr/luajit-2.0.5
        /usr/luajit-205
        /usr/lua-jit-2.0.5
        /usr/lua-jit-205
        /usr/lua
┌─(niluje@illyria:pts/14)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(1:2.73:33%:19:30:%)── file /usr/bin/luajit-2.0.5                                                                                                                                                                                                                                                                                                     ──(Wed, Jan 09)─┘
/usr/bin/luajit-2.0.5: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped
```

-_-"

**Comment by NiLuJe** [comment]
Spoiler alert: it wasn't. -_-"

Trying to match the expected leptonica version...

**Comment by Frenzie** [comment]
Heh, weird.

**Comment by NiLuJe** [comment]
Okay, works fine after rebuilding from a clean tree!

Stuff opens, stuff appears  to reflow, ship it!

**Pull request merged**
